# Generated by Django 3.1 on 2020-08-28 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.DecimalField(decimal_places=6, default=100000.0, max_digits=19)),
                ('active1_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active2_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active3_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active1_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active2_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active3_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('label', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_price', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=19, null=True)),
                ('amount_assets', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_id', models.CharField(max_length=50)),
                ('operation_type', models.BooleanField(default=False)),
                ('operation_status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.room')),
            ],
        ),
    ]
