# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-28 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=6, default=100000.0, max_digits=19)),
                ('active1_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active2_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active3_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active1_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active2_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active3_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
            ],
        ),
    ]
