# Generated by Django 3.1 on 2020-08-26 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200826_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_money', models.DecimalField(decimal_places=10, max_digits=19)),
                ('active1_average_price_date', models.DecimalField(decimal_places=10, max_digits=19)),
                ('active2_average_price_date', models.DecimalField(decimal_places=10, max_digits=19)),
                ('active3_average_price_date', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Transacctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price_opened', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sell_price_closed', models.DecimalField(decimal_places=10, max_digits=19)),
                ('amount_actives', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
