# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_financial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_price', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=19, null=True)),
                ('amount_assets', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_id', models.CharField(max_length=50)),
                ('operation_type', models.BooleanField(default=False)),
                ('operation_status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Financial')),
            ],
        ),
    ]
