# Generated by Django 3.1 on 2020-08-28 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_auto_20200826_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.DecimalField(decimal_places=6, default=100000.0, max_digits=19)),
                ('active1_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active2_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active3_average_price', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active1_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active2_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
                ('active3_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19)),
            ],
        ),
        migrations.DeleteModel(
            name='Money',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='transacctions',
            old_name='amount_actives',
            new_name='amount_assets',
        ),
        migrations.RenameField(
            model_name='transacctions',
            old_name='active_id',
            new_name='asset_id',
        ),
        migrations.RemoveField(
            model_name='transacctions',
            name='buy_price_opened',
        ),
        migrations.RemoveField(
            model_name='transacctions',
            name='sell_price_closed',
        ),
        migrations.AddField(
            model_name='transacctions',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transacctions',
            name='opening_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transacctions',
            name='operation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transacctions',
            name='operation_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transacctions',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
