# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-28 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transacctions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacctions',
            new_name='Transactions',
        ),
    ]
